### ISSUE TITLE
breakpoint are not available on vscode

### ISSUE THREAD

**Issue by sebglon** [number101010/go-kubernetes-vscode-dev#2]
Debug is running. 

on log i can see 
```
2019-04-17T08:58:53Z debug layer=debugger halting
2019-04-17T08:58:53Z debug layer=debugger continuing
```
but breakpoint are always disabled and i have no stack or variables

```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic
```

How can i debug that?

**Comment by sebglon** [comment]
I have found a solution.
it's because on my launch.json i have set a program value to file not a directory

**Comment by joe-elliott** [comment]
Apologies for the late response.  I'm glad you found a solution.  Closing.
